# Generated by Django 4.2.9 on 2024-01-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
