# Generated by Django 5.0 on 2024-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(help_text='Day, when the task should be finished'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Task details'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(help_text='Day, when the task should be started'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=75),
        ),
    ]
