# Generated by Django 5.0 on 2024-01-02 00:56

import apps.todo.models_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_deadline_date_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=apps.todo.models_helpers.create_default_description, max_length=1500, verbose_name='Task details'),
        ),
    ]
