# Generated by Django 5.0 on 2024-01-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_blank_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
