# Generated by Django 5.0 on 2024-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_subtask_started_at_remove_task_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=75),
        ),
    ]
