# Generated by Django 5.0 on 2024-01-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_category_deleted_at_alter_status_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo.task'),
        ),
    ]
