# Generated by Django 5.0 on 2024-01-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_alter_subtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test_blank_field',
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(blank=True, null=True),
        ),
    ]
