# Generated by Django 5.0 on 2024-01-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_task_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.category'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline_date',
            field=models.DateField(auto_now_add=True, help_text='Day, when the task should be finished'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='start_date',
            field=models.DateField(auto_now_add=True, help_text='Day, when the task should be started'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(default=1, limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo.task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(default='DEFAULT SUBTASK', max_length=75),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(auto_now_add=True, help_text='Day, when the task should be finished'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(auto_now_add=True, help_text='Day, when the task should be started'),
        ),
    ]
