# Generated by Django 5.0 on 2024-01-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_alter_subtask_category_alter_subtask_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(help_text='Day, when the task should be finished'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(help_text='Day, when the task should be started'),
        ),
    ]
