# Generated by Django 5.0 on 2024-01-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_alter_task_deadline_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='todo.status'),
        ),
    ]
