# Generated by Django 5.0 on 2024-01-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_subtask_note_alter_subtask_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='note',
            field=models.CharField(blank=True, default=2, max_length=250),
            preserve_default=False,
        ),
    ]
