# Generated by Django 5.0 on 2024-01-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_alter_subtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Day, when the task should be finished', null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='start_date',
            field=models.DateField(blank=True, help_text='Day, when the task should be started', null=True),
        ),
    ]
