# Generated by Django 5.0 on 2024-01-18 02:18

import apps.todo.models_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_alter_subtask_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Day, when the task should be finished', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=apps.todo.models_helpers.create_default_description, max_length=1500, null=True, verbose_name='Task details'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Day, when the task should be started', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=models.SET(1), to='todo.status'),
        ),
    ]
