# Generated by Django 5.0.1 on 2024-01-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_alter_subtask_category_alter_subtask_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.category'),
        ),
    ]
